config/routes.rb
Freebnb::Application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy] do
    resources :rooms, only: :index
    resources :room_requests, only: [:index]
    resources :message_threads, only: :index
    get  "/dashboard" => "dashboard#root"
  end

  resources :rooms do
    resources :room_requests, only: [:new, :create]
    get "manage", on: :member
    resources :availabilities, only: [:new]
  end

  resources :room_requests, only: [:show, :destroy, :update] do
    post "approve", on: :member
    post "deny", on: :member
    post "cancel", on: :member
  end

  resources :notifications, only: [:index, :show]

  resources :reviews, only: [:create, :detroy]

  resources :messages, only: [:create]

  resources :message_threads, only: :show

  resources :availabilities, only: [:create]

  get '/search' => 'pages#search'

  root to: "rooms#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  include Reviewable

  attr_reader :password

  before_validation :ensure_session_token

  validates :email,:session_token, presence: true, uniqueness: :true
  validates :fname, :lname, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  # validates :gender, inclusion: { in: %w(M F O), allow_nil: true }
  # ^ didn't allow nil

  has_many(
    :listings,
    class_name: "Room",
    foreign_key: :owner_id,
    primary_key: :id,
    inverse_of: :owner,
    dependent: :destroy  )

  has_many(
    :requests_to_stay,
    class_name: "RoomRequest",
    foreign_key: :guest_id,
    primary_key: :id,
    inverse_of: :guest,
    dependent: :destroy  )

  has_many(
    :authored_reviews,
    class_name: "Review",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :author,
    dependent: :destroy  )

  has_many :room_requests, through: :listings, source: :room_requests, dependent: :destroy

  has_many(
    :notifications,
    class_name: "Notification",
    foreign_key: :user_id,
    primary_key: :id  )

  has_many(
    :sent_messages,
    class_name: "Message",
    foreign_key: :sender_id,
    primary_key: :id,
    inverse_of: :sender,
    dependent: :destroy  )

  has_many(
    :received_messages,
    class_name: "Message",
    foreign_key: :recipient_id,
    primary_key: :id,
    inverse_of: :recipient,
    dependent: :destroy  )

    def threads
      MessageThread.where("user_one_id = :id OR user_two_id = :id", id: self.id)
    end

  has_attached_file :avatar, styles: { thumb: "100x100#", profile: "230x230#" },
  default_url: "https://s3.amazonaws.com/freebnb_dev/users/avatars/000/000/default_avatar/default_avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def User.find_by_credentials(email, secret)
    @user = User.find_by_email(email)
    return @user if @user && @user.is_password?(secret)
    nil
  end

  def User.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def owns_room?(room)
    room.owner_id == self.id
  end

  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    bcrypt = BCrypt::Password.new(self.password_digest)
    bcrypt.is_password?(secret)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
    def ensure_session_token
      self.session_token ||= User.generate_session_token
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      flash[:notice] = ["Welcome, #{ @user.fname }!"]
      redirect_to edit_user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order("created_at DESC")

    if request.xhr?
      render "users/user"
    else
      render :show
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if request.xhr?
        puts "**********************FUN****************************"
        render json: @user
      else
        flash[:notice] = ["Your profile has been updated"]
        redirect_to @user
      end
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :password, :email,
      :avatar, :birthdate, :description, :phone_number, :gender)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar_upload.html.erb
<form enctype="multipart/form-data" action="<%= user_url %>" method="post">
  <%= auth_token %>

  <input type="file" name="user[avatar]">

  <p><input type="submit" value="Upload Image"></p>
</form>

app/views/users/edit.html.erb
<h2>Improve Your Profile (Optional)</h2>
<br>

<form enctype="multipart/form-data" action="<%= user_url(@user) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">

  <%= auth_token %>

  <label for="avatar-upload"><strong>Upload / Change Your Profile Image</strong></label>
  <% if @user.avatar.exists? %>
    <img src="<%= @user.avatar.url(:thumb) %>"><br>
  <% end %>
  <input type="file" name="user[avatar]" id="avatar-upload">

<br><br>

  <label for="first_name">First Name</label>
  <input type="text"
  name="user[fname]" value="<%= @user.fname %>" id="first_name">

  <label for="last_name">Last Name</label>
  <input type="text" name="user[lname]" value="<%= @user.lname %>" id="last_name">

  <label for="email">Email</label>
  <input type="text" name="user[email]" value="<%= @user.email %>" id="email">

  <label for="birthdate">Birthdate</label>
  <input type="date" name="user[birthdate]" value="<%= @user.birthdate %>" id="birthdate">

  <label for="user_description" >Describe Yourself</label>
  <textarea name="user[description]" id="user_description"><%= @user.description %></textarea>

  <label for="phone_number">Phone Number</label>
  <input type="number" name="user[phone_number]"
  value="<%= @user.phone_number %>" id="phone_number">

  <label for="gender">Gender</label>
  <select name="user[gender]" id="gender">
    <option value=""></option>
    <option value="F" <%= "selected" if @user.gender == "F" %> >Female</option>
    <option value="M" <%= "selected" if @user.gender == "M" %> >Male</option>
    <option value="O" <%= "selected" if @user.gender == "O" %>>Other</option>
  </select>

<br><br>
  <p><input type="submit" value="Save Changes"></p>
</form>

app/views/users/new.html.erb
<h2>Sign Up</h2><br>

<form action="<%= users_url %>" method="post">

  <%= auth_token %>
  <div class="input">
    <label for="first_name">First Name</label>
    <input type="text" name="user[fname]" value="" id="first_name">
  </div>

  <div class="input">
  <label for="last_name">Last Name</label>
  <input type="text" name="user[lname]" value="" id="last_name">
  </div>

  <div class="input">
  <label for="email">Email</label>
  <input type="email" name="user[email]" value="" id="email">
  </div>

  <div class="input">
  <label for="password">Password</label>
  <input type="password" name="user[password]" value="" id="password">
  </div>

  <br>

  <p><input type="submit" value="Sign Up"></p>
</form>

app/views/users/show.html.erb
<section class="profile-sidebar">
  <div class="profile-picture">
    <img src="<%= @user.avatar.url(:profile) %>" class="profile-thumb">
  </div>

  <% if signed_in? %>
    <h3>Send <%= @user.fname %> a Message</h3>
    <div class="message-form">
      <%= render partial: "messages/form", locals: { recipient_id: @user.id } %>
    </div>
  <% else %>
    <p class="sign-in-prompt"><a class="open-modal" href="<%= new_session_url %>">Sign in</a> to send <%= @user.fname %> a message or write a review.<p>
  <% end %>
</section>



<section class="profile-content">


  <h1>Hey, I'm <%= @user.fname.capitalize %>!</h1>

  <div class="profile-info">
    <%= "Member since #{ format_member_since(@user.created_at) }." %>
  </div>

  <article class="profile-description">
    <p><%= @user.description %></p>
  </article>

  <% if signed_in? %>
    <%= render "reviews/form", reviewable_type: "User", reviewable_id: @user.id %>
  <% end %>



  <% unless @reviews.empty? %>

    <section class="user-reviews group">
      <h3 class="reviews-title">Reviews</h3>

      <% @reviews.each do |review| %>

        <article class="review">
          <header class="group">

            <div class="review-thumb">
              <a href="<%= user_url(review.author) %>">
                <img src="<%= review.author.avatar.url %>" width="54" height="54">
              </a>
            </div>
            <div class="review-info">
              <h4><a href="<%= user_url(review.author) %>"><%= "#{review.author.fname} #{review.author.lname}" %></a></h4>
              <time><%= "#{time_ago_in_words(review.created_at)} ago." %></time>
            </div>

          </header>

            <div class="review-text">
              <p>
                <%= review.body %>
              </p>
            </div>

        </article>

      <% end %>

    </section>

  <% else %>
    <br>
    <h3>There are currently no reviews for this user.</h3>

  <% end %>

</section>