config/routes.rb
Freebnb::Application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy] do
    resources :rooms, only: :index
    resources :room_requests, only: [:index]
    resources :message_threads, only: :index
    get  "/dashboard" => "dashboard#root"
  end

  resources :rooms do
    resources :room_requests, only: [:new, :create]
    get "manage", on: :member
    resources :availabilities, only: [:new]
  end

  resources :room_requests, only: [:show, :destroy, :update] do
    post "approve", on: :member
    post "deny", on: :member
    post "cancel", on: :member
  end

  resources :notifications, only: [:index, :show]

  resources :reviews, only: [:create, :detroy]

  resources :messages, only: [:create]

  resources :message_threads, only: :show

  resources :availabilities, only: [:create]

  get '/search' => 'pages#search'

  root to: "rooms#index"

end

app/models/room.rb
require 'active_support/inflector'

class Room < ActiveRecord::Base
  include Reviewable

  include PgSearch
  pg_search_scope :search_by_region, against: :address_region

  validates :home_type, :room_type, presence: true
  validates :num_possible_guests, :address_region, :address_country, presence: true

  geocoded_by :full_address
  after_validation :geocode

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :owner_id,
    inverse_of: :listings,
    primary_key: :id  )

  has_many(
    :room_requests,
    class_name: "RoomRequest",
    foreign_key: :room_id,
    primary_key: :id,
    inverse_of: :room,
    dependent: :destroy  )

  has_many :availabilities, inverse_of: :room, dependent: :destroy

  has_many :pictures, inverse_of: :room, dependent: :destroy

  def approved_requests
    self.room_requests.where(status: "APPROVED")
  end

  def full_address
    "#{ self.street_address }, #{ self.address_city }, #{ self.address_zip_code } #{ self.address_country }"
  end

  def display_title
    (self.title? && !self.title.empty?) ? self.title :
    "#{ ActiveSupport::Inflector.titleize(self.home_type) } in #{ ActiveSupport::Inflector.titleize(self.address_city) }"
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :require_signed_in!, only: [:new, :create, :manage]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @listings = @user.listings.order("created_at DESC")
      if request.xhr?
        render "rooms/listings"
      else
        render :user_index
      end
    else
      if current_user
        @listings = Room.where("owner_id != ?", current_user.id)
      else
        @listings = Room.all
      end
      @feature_one = Room.find(9) # 9
      @feature_two = Room.find(19) # 19
      @feature_three = Room.find(5) # 5

      render :index
    end
  end

  def new
    @room = Room.new
    render :new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to edit_room_url(@room)
    else
      flash.now[:errors] = @room.errors.full_messages
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
    @reviews = @room.reviews.order("created_at DESC")
    @owner = @room.owner
    render :show
  end

  def edit
    @room = Room.find(params[:id])
    render :edit
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)
      if params[:pictures]
        params[:pictures][:images].each do |image|
          @room.pictures.create!({ image: image })
        end
      end

      redirect_to @room
    else
      flash.now[:errors] = @room.errors.full_messages
      render :edit
    end
  end

  def manage
    @room = Room.find(params[:id])
    @requests = @room.room_requests.where("status != 'CANCELLED' AND status != 'DENIED'" )
    @owner = @room.owner
    render :manage
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    head :ok
  end


  private
    def room_params
      params.require(:room).permit(:owner_id, :home_type, :room_type,
      :num_possible_guests, :address_city, :address_region,
      :street_address, :address_zip_code, :title, :description,
      :num_bedrooms, :num_bathrooms, :price_per_night, :address_country )
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<a href="<%= room_url(room) %>" data-room-id="<%= room.id %>">
  <div class="room-container group">

    <figure class="room-image-default">
      <% unless room.pictures.empty? %>
        <img src="<%= room.pictures.sample.image.url(:profile) %>">
      <% else %>
        <img src="<%= Picture.new.image.url(:profile) %>">
      <% end %>
    </figure>

    <figure class="owner-photo">
      <img src="<%= room.owner.avatar.url(:thumb) %>">
    </figure>

    <article class="room-info-small">
      <%= MAKE_NICE[room.room_type] %><br>
      <%= "#{ room.display_title }" %>
    </article>


  </div>
</a>

app/views/rooms/edit.html.erb
<h2>Edit Your Listing (Optional)</h2>

<form action="<%= room_url(@room) %>"
  enctype="multipart/form-data" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>

  <% unless @room.pictures.empty? %>
    <% @room.pictures.each do |picture| %>
      <img src="<%= picture.image.url(:thumb_big) %>">
    <% end %>
  <% end %>

  <input type="hidden" name="room[owner_id]" value="<%= current_user.id %>">

  <label for="image-upload">Select Photos to Upload</label>
  <input type="file" name="pictures[images][]" id="image-upload" multiple>

  <label for="title">Title</label>
  <input type="text" name="room[title]" value="<%= @room.title %>" id="title">

  <label for="price_per_night">Price Per Night: $</label>
  <input type="number" name="room[price_per_night]" min="1" max="2000"
  value="<%= @room.price_per_night %>" id="price_per_night">

  <br><br>

  <label for="room_description">Description</label><br>
    <textarea name="room[description]" rows="8" cols="40" id="room_description">
      <%= @room.description %>
    </textarea>

<br><br>

Add Some Information About Your Listing's Location <br><br>

  <label for="street_address">Street Address:</label>
  <input type="text" name="room[street_address]"
  value="<%= @room.street_address %>" id="street_address">

  <br><br>

    <label for="country">Country</label>
    <input type="text" name="room[address_country]" value="<%= @room.address_country %>" id="country">

  <br><br>

  <label for="city">City</label>
  <input type="text" name="room[address_city]" value="<%= @room.address_city %>" id="city">


<br><br>

  <label>
    <select name="room[address_region]">
      <option value="">Choose a Region</option>

      <option value="north_america"
        <%= "selected" if @room.address_region == "north_america" %> >
        North America
      </option>
      <option value="hawaii"
        <%= "selected" if @room.address_region == "hawaii" %> >
        Hawaii
      </option>
      <option value="europe"
        <%= "selected" if @room.address_region == "europe" %> >
        Europe
      </option>
      <option value="east_asia"
        <%= "selected" if @room.address_region == "east_asia" %> >
        East Asia
      </option>
      <option value="south_america"
        <%= "selected" if @room.address_region == "south_america" %> >
        South America
      </option>
    </select>

  </label>


<br>
  <label for="address_zip_code">Zip Code</label>
  <input type="number" name="room[address_zip_code]"
  value="<%= @room.address_zip_code %>" id="address_zip_code">

<br><br>


  <label for="country">Country</label>
  <input type="text" name="room[address_country]" value="<%= @room.address_country %>" id="country">

<br><br>

  <label for="home_type">Home Type</label>
  <input type="text" name="room[home_type]" value="<%= @room.home_type %>" id="home_type">

<br><br>

  Room Type: <br><br>
  <label>
    Entire House / Apt.
    <input type="radio" name="room[room_type]"
    <%= "checked" if @room.room_type == "entire_space" %> value="entire_space">
  </label>
  <label>
    Private Room
    <input type="radio" name="room[room_type]"
    <%= "checked" if @room.room_type == "private_room" %> value="private_room">
  </label>
  <label>
    Shared Room
    <input type="radio" name="room[room_type]"
    <%= "checked" if @room.room_type == "shared_room" %> value="shared_room">
  </label>

<br><br>

  <label>
    Number of Guests
    <select name="room[num_possible_guests]">
      <option value=""></option>
      <% (1..10).to_a.each do |num|  %>
        <option value="<%= num %>"
          <%= "selected" if @room.num_possible_guests == num %> >
          <%= num %>
        </option>
      <% end %>
    </select>
  </label>

  <label>
    Number of Bedrooms
    <select name="room[num_bedrooms]">
      <option value=""></option>
      <% (1..10).to_a.each do |num|  %>
        <option value="<%= num %>"
          <%= "selected" if @room.num_bedrooms == num %> >
          <%= num %>
        </option>
      <% end %>
    </select>
  </label>

  <label>
    Number of Bathrooms
    <select name="room[num_bathrooms]">
      <option value=""></option>
      <% (1..10).to_a.each do |num|  %>
        <option value="<%= num %>"
          <%= "selected" if @room.num_bathrooms == num %> >
          <%= num %>
        </option>
      <% end %>
    </select>
  </label>

  <p><input type="submit" value="Update Your Listing!"></p>
</form>

app/views/rooms/index.html.erb
<div id="front-page-tagline">
  <h1 class="tagline">Find a place to stay. In a tree.</h1>
  <div class="main-search-bar">
    <%= render "pages/search" %>
  </div>
</div>


<div class="front-page-img">
  <img src="https://s3.amazonaws.com/freebnb_dev/front_page/front-page-mirror-house.jpg">
</div>


<h2 class="featured">Featured Tree Houses</h2>
<div class="featured-subtitle">
  Not sure where to start? Check out these featured spaces!
</div>

<section class="home-page-articles group">
  <article class="home-page group">

    <a href="<%= room_url(@feature_one) %>">
      <img src="<%= @feature_one.pictures.first.image(:profile) %>">
      <div class="featured-room-title">
        <%= @feature_one.display_title %>
      </div>
    </a>


    <h3 class="text-special">Travel</h3>
    <p>
      From apartments and rooms to tree houses and tree villages: stay in unique spaces all over the world.
    </p>
  </article>

  <article class="home-page group">

    <a href="<%= room_url(@feature_two) %>">
      <img src="<%= @feature_two.pictures.first.image(:profile) %>">
      <div class="featured-room-title" id="feature-title-two">
        <%= @feature_two.display_title %>
      </div>
    </a>


    <h3 class="text-special">Host</h3>
    <p>
      Having a tree house is great, and it's even better when you get to share it. Join the community today!
    </p>
  </article>

  <article class="home-page group">

    <a href="<%= room_url(@feature_three) %>">
      <img src="<%= @feature_three.pictures.first.image(:profile) %>">
      <div class="featured-room-title" id="feature-title-three">
        <%= @feature_three.display_title %>
      </div>
    </a>


    <h3 class="text-special">Travel and Safety</h3>
    <p>
      From Verified ID to our worldwide customer support team, we've got your back.
    </p>
  </article>

app/views/rooms/manage.html.erb
<script>

  $(document).ready(function(){

    var Carrousel = (function(){

      var delay;
      var carrousel;
      var itemsHolder;
      var items;
      var itemWidth;
      var currentItem;
      var timerId;

      var nextButton;
      var previousButton;
      var numberLabel;

      var init = function(){
        delay = 10000;
        carrousel = $("#carrousel");
        itemsHolder = carrousel.find("> ul");
        items = itemsHolder.find("> li");
        itemWidth = items.first().width();
        currentItem = -1;
        nextButton = $("#carrousel-nav > .next");
        previousButton = $("#carrousel-nav > .previous");
        numberLabel = $("#carrousel-nav > .number");
        itemsHolder.css({"width": (items.length * itemWidth) + "px"});
        bind();
        start();
      };

      var bind = function(){
        nextButton.on("click", next);
        previousButton.on("click", previous);
      }

      var start = function(){
        loop();
        timerId = window.setInterval(loop, delay);
      }

      var stop = function(){
        if(timerId){
          window.clearInterval(timerId);
        }
      }

      var loop = function(){
        next();
      }

      var next = function(){
        currentItem++;

        if(currentItem == items.length){
          currentItem = 0;
        }

        move();
      };

      var previous = function(){
        currentItem--;

        if(currentItem <= 0){
          currentItem = items.length - 1;
        }

        move();
      }

      var move = function(){
        var html = (currentItem + 1) + " / " + items.length;
        numberLabel.html(html);

        var leftPosition = currentItem * itemWidth * -1;
        itemsHolder.stop().animate({"left": leftPosition + "px"}, 1000);
      }

      return {
        init: init,
        next: next,
        previous: previous,
        start: start,
        stop: stop
      }
    })();
    Carrousel.init();


    $('#delete-room-link').click(function (event) {
      if (confirm("Are you sure you want to delete this listing?")) {
        event.preventDefault();
        $.ajax({
          url: "<%= room_url(@room) %>",
          type: "delete",
          success: function () {
            window.location.href = "<%= user_rooms_url(current_user) %>"
            alert("Your listing has been successfully deleted.")
          }
        });
      } else {
        event.preventDefault();
      };
    })

  });

</script>



<h1>Manage Your Listing</h1>


<!-- ROOM SHOW MAIN CONTENT -->

    <!-- header and pictures -->

<section class="room-show-main">

  <header class="room-show">
    <h2><%= @room.display_title %></h2>
  </header>


<div class="manage-buttons">

  <% if signed_in? && current_user.id == @room.owner_id %>
      <a href="<%= room_url(@room) %>"><i class="fa fa-home"></i> View</a>
      <a href="<%= edit_room_url(@room) %>"><i class="fa fa-pencil-square-o"></i> Edit</a>
      <a href="<%= new_room_availability_url(@room) %>"><i class="fa fa-calendar"></i> Add Availability</a>
  <% end %>

</div>


    <!-- photo carousel -->


  <% unless @room.pictures.empty? %>
    <div id="carrousel">
       <ul>    <!-- <ul class="group"> -->
        <% @room.pictures.each do |picture| %>
          <li>
            <figure class="room-show-image">
              <img src="<%= picture.image.url(:profile) %>">
            </figure>
          </li>
        <% end %>
      </ul>
    </div>

    <div id="carrousel-nav">
      <span class="previous">Previous</span> &mdash;
      <strong class="number">0 / 0</strong> &mdash;
      <span class="next">Next</span>
    </div>

  <% else %>
      <figure class="room-image-default">
        <img src="<%= Picture.new.image.url(:profile) %>">
        <figcaption>
          <%= "#{ @room.address_city }, #{ @room.address_country }" %>
        </figcaption>
      </figure>
  <% end %>
<br>



  <!-- Room Information -->

<section class="room-info group">

  <h3>The space</h3>
  <p><%= @room.description %></p>

  <table id="room-details">
      <tr>
          <th>Home Type:</th>
          <td><%= @room.home_type %></td>
      </tr>
      <tr>
          <th>Room Type:</th>
          <td><%= MAKE_NICE[@room.room_type] %></td>
      </tr>
      <tr>
          <th>Accomodates:</th>
          <td><%= @room.num_possible_guests %></td>
      </tr>
      <tr>
          <th>Bedrooms:</th>
          <td><%= @room.num_bedrooms %></td>
      </tr>
      <tr>
          <th>Bathrooms:</th>
          <td><%= @room.num_bathrooms %></td>
      </tr>
      <tr>
          <th>City</th>
          <td><%= @room.address_city %></td>
      </tr>
      <tr>
          <th>Country</th>
          <td><%= @room.address_country %></td>
      </tr>
  </table>

  </section>

  <h3 class="scary"><a href="<%= room_url(@room) %>" id="delete-room-link"><i class="fa fa-exclamation-triangle"></i> Remove Listing</a>

</section>


  <!-- ROOM SHOW SIDEBAR -->


<section class="room-show-sidebar group">

  <h2>Current Availability</h2>

  <%= render "layouts/calendar", room: @room  %>

    <% if @room.availabilities.empty? %>
      <h3>You haven't made this space available yet.</h3>
    <% end %>


<a href="<%= new_room_availability_url(@room) %>"><i class="fa fa-calendar"></i> Add Availability</a>


  <% unless @requests.empty? %>
    <h2 id="req-to-stay">Current Requests:</h2>

    <section class="manage-requests">

      <% @requests.each do |request| %>
        <article class="request group">

          <p class="status">Status: <strong><%= request.status %></strong></p>

          <p class="request-details-manage">
            <strong>Dates:</strong><br>
            <%= format_time(request.start_date)%> to<br>
            <%= format_time(request.end_date) %><br><br>
            <strong>Number of Guests:</strong> <%= request.num_guests %><br>
          </p>


        <% if request.status == "PENDING" &&
                                current_user && request.room.owner_id == current_user.id %>
          <br>
          <div class="manage-request">
              <form action="<%= user_url(request.guest) %>" method="get">
                <p><input type="submit" value="View Guest Profile"></p>
              </form>

              <form action="<%= approve_room_request_url(request) %>" method="post">
                <%= auth_token %>
                <p><input type="submit" value="Approve"></p>
              </form>

              <form action="<%= deny_room_request_url(request) %>" method="post">
                <%= auth_token %>
                <p><input type="submit" value="Deny"></p>
              </form><br><br>
          </div>
        <% end %>


          <time>
            <%= " Made #{ time_ago_in_words(request.created_at) } ago by" %>
            <a href="<%= user_url(request.guest) %>">
              <%= "#{ request.guest.fname } #{ request.guest.lname }." %>
            </a>
          </time>


        </article>

      <% end %>


    <% else %>
      <br><br>
      <h3>There are currently no requests to stay at this property.</h3>

    <% end %>

  </section>

</section>

app/views/rooms/new.html.erb
<h2>List Your Place</h2>

<form action="<%= rooms_url %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="room[owner_id]" value="<%= current_user.id %>">

  <label>
    <select name="room[address_region]">
      <option value="">Choose a Region</option>

      <option value="north_america"
        <%= "selected" if @room.address_region == "north_america" %> >
        North America
      </option>
      <option value="hawaii"
        <%= "selected" if @room.address_region == "hawaii" %> >
        Hawaii
      </option>
      <option value="europe"
        <%= "selected" if @room.address_region == "europe" %> >
        Europe
      </option>
      <option value="east_asia"
        <%= "selected" if @room.address_region == "east_asia" %> >
        East Asia
      </option>
      <option value="south_america"
        <%= "selected" if @room.address_region == "south_america" %> >
        South America
      </option>
    </select>

  </label>

  <br>

  <label for="country">Country</label>
  <input type="text" name="room[address_country]" value="<%= @room.address_country %>" id="country">

<br><br>

  <label for="city">City</label>
  <input type="text" name="room[address_city]" value="<%= @room.address_city %>" id="city">

<br><br>

  <label for="home_type">Home Type</label>
  <input type="text" name="room[home_type]" value="<%= @room.home_type %>" id="home_type">


<br><br>

  Room Type: <br><br>
  <label>
    Entire House / Apt.
    <input type="radio" name="room[room_type]"
    <%= "checked" if @room.room_type == "entire_space" %> value="entire_space">
  </label>
  <label>
    Private Room
    <input type="radio" name="room[room_type]"
    <%= "checked" if @room.room_type == "private_room" %> value="private_room">
  </label>
  <label>
    Shared Room
    <input type="radio" name="room[room_type]"
    <%= "checked" if @room.room_type == "shared_room" %> value="shared_room">
  </label>

<br>

  <label>
    Number of Guests
    <select name="room[num_possible_guests]">
      <option value=""></option>
      <% (1..10).to_a.each do |num|  %>
        <option value="<%= num %>"
          <%= "selected" if @room.num_possible_guests == num %> >
          <%= num %>
        </option>
      <% end %>
    </select>
  </label>
  <br><br>

  <p><input type="submit" value="Create Your Listing!"></p>
</form>

app/views/rooms/show.html.erb
<script>

  $(document).ready(function(){

    var Carrousel = (function(){

      var delay;
      var carrousel;
      var itemsHolder;
      var items;
      var itemWidth;
      var currentItem;
      var timerId;

      var nextButton;
      var previousButton;
      var numberLabel;

      var init = function(){
        console.log("init")
        delay = 10000;
        carrousel = $("#carrousel");
        itemsHolder = carrousel.find("> ul");
        items = itemsHolder.find("> li");
        itemWidth = items.first().width();
        currentItem = -1;
        nextButton = $("#carrousel-nav > .next");
        previousButton = $("#carrousel-nav > .previous");
        numberLabel = $("#carrousel-nav > .number");
        itemsHolder.css({"width": (items.length * itemWidth) + "px"});
        bind();
        start();
      };

      var bind = function(){
        nextButton.on("click", next);
        previousButton.on("click", previous);
      }

      var start = function(){
        loop();
        timerId = window.setInterval(loop, delay);
      }

      var stop = function(){
        if(timerId){
          window.clearInterval(timerId);
        }
      }

      var loop = function(){
        next();
      }

      var next = function(){
        currentItem++;

        if(currentItem == items.length){
          currentItem = 0;
        }

        move();
      };

      var previous = function(){
        // console.log("going back");
        // console.log(currentItem)
        currentItem--;
        // console.log(currentItem)

        if(currentItem <= 0){
          currentItem = items.length - 1;
        }

        move();
      }

      var move = function(){
        // console.log("move")
        var html = (currentItem + 1) + " / " + items.length;
        numberLabel.html(html);

        var leftPosition = currentItem * itemWidth * -1;
        itemsHolder.stop().animate({"left": leftPosition + "px"}, 1000);
      }

      return {
        init: init,
        next: next,
        previous: previous,
        start: start,
        stop: stop
      }
    })();
    Carrousel.init();

  });

</script>


<!-- ROOM SHOW MAIN CONTENT -->

    <!-- header and pictures -->

<section class="room-show-main">

  <header class="room-show">
    <h1>
      <%= @room.display_title %>
    </h1>
  </header>


    <!-- photo carousel -->


  <% unless @room.pictures.empty? %>
    <div id="carrousel">
       <ul>    <!-- <ul class="group"> -->
        <% @room.pictures.each do |picture| %>
          <li>
            <figure class="room-show-image">
              <img src="<%= picture.image.url(:profile) %>">
            </figure>
          </li>
        <% end %>
      </ul>
    </div>

    <div id="carrousel-nav">
      <strong class="number">0 / 0</strong>
      <span class="next">Next</span>
    </div>

  <% else %>
      <figure class="room-image-default">
        <img src="<%= Picture.new.image.url(:profile) %>">
        <!-- <i id="default-room-icon" class="fa fa-home fa-5x fa-fw"></i> -->
        <figcaption>
          <%= "#{ @room.address_city }, #{ @room.address_country }" %>
        </figcaption>
      </figure>
  <% end %>


  <!-- Room Information -->

  <% if signed_in? && current_user.id == @room.owner.id %>
    <a class="manage-link" href="<%= manage_room_url(@room) %>">Manage</a> your listing.
  <% end %>

  <section class="room-info group">

  <h3>The space</h3>
  <p><%= @room.description %></p>

  <table id="room-details">
      <tr>
          <th>Home Type:</th>
          <td><%= @room.home_type %></td>
      </tr>
      <tr>
          <th>Room Type:</th>
          <td><%= MAKE_NICE[@room.room_type] %></td>
      </tr>
      <tr>
          <th>Accomodates:</th>
          <td><%= @room.num_possible_guests %></td>
      </tr>
      <tr>
          <th>Bedrooms:</th>
          <td><%= @room.num_bedrooms %></td>
      </tr>
      <tr>
          <th>Bathrooms:</th>
          <td><%= @room.num_bathrooms %></td>
      </tr>
      <tr>
          <th>City</th>
          <td><%= @room.address_city %></td>
      </tr>
      <tr>
          <th>Country</th>
          <td><%= @room.address_country %></td>
      </tr>
  </table>

  </section>

  <!-- Reviews & New Review Form -->


  <% if signed_in? %>
    <%= render "reviews/form", reviewable_type: "Room", reviewable_id: @room.id %>
  <% else %>
    <p class="sign-in-prompt"><a class="open-modal" href="<%= new_session_url %>">Sign in</a> to write a review.<p>
  <% end %>

  <% unless @reviews.empty? %>

    <section class="room-reviews group">

      <h3 class="reviews-title">Reviews</h3>

      <% @reviews.each do |review| %>

        <article class="review">
          <header class="group">

            <div class="review-thumb">
              <a href="<%= user_url(review.author) %>">
                <img src="<%= review.author.avatar.url %>" width="54" height="54">
              </a>
            </div>
            <div class="review-info">
              <h4><a href="<%= user_url(review.author) %>"><%= "#{review.author.fname} #{review.author.lname}" %></a></h4>
              <time><%= "#{time_ago_in_words(review.created_at)} ago." %></time>
            </div>

          </header>

            <div class="review-text">
              <p>
                <%= review.body %>
              </p>
            </div>

        </article>

      <% end %>

    </section>
  <% else %>
    <br>
    <h3>There are currently no reviews for this listing.</h3>

  <% end %>
</section>




  <!-- ROOM SHOW SIDEBAR -->


<section class="room-show-sidebar group">

  <h2>Availability</h2>

  <%= render "layouts/calendar", room: @room  %>

  <% if signed_in? %>
    <% unless @room.availabilities.empty? %>

    <h3>Make a Request</h3>
    <br>

    <form action="<%= room_room_requests_url(@room) %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="request[guest_id]" value="<%= current_user.id %>">
      <input type="hidden" name="request[room_id]" value="<%= @room.id %>">
      <input type="hidden" name="request[status]" value="PENDING">

      <label for="start_date">Start Date</label>
      <input type="date" name="request[start_date]" value="" id="start_date">

      <label for="end_date">End Date</label>
      <input type="date" name="request[end_date]" value="" id="end_date">

      <label for="num_guests">Number of Guests</label>
      <select name="request[num_guests]" id="num_guests">
        <% (1..10).to_a.each do |num| %>
          <option value="<%= num %>"><%= num %></option>
        <% end %>
      </select>
    <br><br>
      <p><input type="submit" value="You make that request!"></p>
    </form>

    <% else %>

    <h3>This room's owner hasn't made it available yet.</h3>

    <% end %>

  <% else %>
    <p class="sign-in-prompt">Please <a class="open-modal" href="<%= new_session_url %>">sign in</a> to request this space.<p>
  <% end %>



  <!-- Host Info -->


  <div class="owner-info group">

      <img src="<%= @owner.avatar.url(:profile) %>">


      <h3><%= @owner.fname.capitalize %></h3>

      <a href="<%= user_url(@owner) %>">More about the host &#10154</a>

    </div>

</section>

app/views/rooms/user_index.html.erb
<h2>Your Listings</h2>

<% @listings.each do |room| %>

    <%= room.display_title %><br>
  <a href="<%= room_url(room) %>">
    View Listing
  </a>
  <% if current_user.id == room.owner_id %> |
    <a href="<%= manage_room_url(room) %>">Manage Listing</a>
  <% end %>
  <br><br>


<% end %>

<br><br>