config/routes.rb
Freebnb::Application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy] do
    resources :rooms, only: :index
    resources :room_requests, only: [:index]
    resources :message_threads, only: :index
    get  "/dashboard" => "dashboard#root"
  end

  resources :rooms do
    resources :room_requests, only: [:new, :create]
    get "manage", on: :member
    resources :availabilities, only: [:new]
  end

  resources :room_requests, only: [:show, :destroy, :update] do
    post "approve", on: :member
    post "deny", on: :member
    post "cancel", on: :member
  end

  resources :notifications, only: [:index, :show]

  resources :reviews, only: [:create, :detroy]

  resources :messages, only: [:create]

  resources :message_threads, only: :show

  resources :availabilities, only: [:create]

  get '/search' => 'pages#search'

  root to: "rooms#index"

end

app/models/room_request.rb
class RoomRequest < ActiveRecord::Base

  STATUS_STATES = [
    "APPROVED",
    "PENDING",
    "CANCELLED",
    "DENIED"
  ]

  validates :num_guests, :start_date, :end_date, presence: true
  validates :status, inclusion: STATUS_STATES
  validate :check_availability
  validate :does_not_overlap_approved_request

  belongs_to(
    :guest,
    class_name: "User",
    foreign_key: :guest_id,
    inverse_of: :requests_to_stay,
    primary_key: :id  )

  belongs_to(
    :room,
    class_name: "Room",
    foreign_key: :room_id,
    inverse_of: :room_requests,
    primary_key: :id  )

  has_many :notifications, as: :notifiable, dependent: :destroy

  has_one :host, through: :room, source: :owner

  def new_request_notification
    self.notifications.unread.create!({
      event_id: EVENT_IDS[:new_room_request], user_id: self.host.id })
  end

  def approved?
    self.status == "APPROVED"
  end

  def denied?
    self.status == "DENIED"
  end

  def pending?
    self.status == "PENDING"
  end

  def deny!
    self.status = "DENIED"
    self.save!
    self.notifications.unread.create!({
      event_id: EVENT_IDS[:request_denied], user_id: self.guest_id })
  end

  def cancel!
    self.status = "CANCELLED"
    self.save!
  end

  def approve!
    # raise "not pending" unless self.status == "PENDING"
    transaction do
      self.status = "APPROVED"
      self.save!
      self.notifications.unread.create!({
        event_id: EVENT_IDS[:request_approved], user_id: self.guest_id })

      overlapping_pending_requests.each do |req|
        req.status = "DENIED"
        req.save!
      end
    end
  end

  private

  def check_availability
    conditions = <<-SQL
      ((room_id = :room_id)
        AND (start_date <= :start_date)
        AND (end_date >= :end_date))
    SQL

    overlapping_availabilities = Availability.where(conditions, {
      room_id: self.room_id,
      start_date: self.start_date,
      end_date: self.end_date
    })

    if overlapping_availabilities.empty?
      errors[:base] << "The room is not available during those dates."
    end
  end

  def assign_pending_status
    self.status ||= "PENDING"
  end

  def overlapping_requests
    conditions = <<-SQL
      ((room_id = :room_id)
        AND (start_date <= :end_date)
        AND (end_date >= :start_date))
    SQL

    overlapping_requests = RoomRequest.where(conditions, {
      room_id: self.room_id,
      start_date: self.start_date,
      end_date: self.end_date
    })

    if self.id.nil?
      overlapping_requests
    else
      overlapping_requests.where("id != ?", self.id)
    end
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def does_not_overlap_approved_request
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] << "Request conflicts with existing approved request"
    end
  end

end

app/controllers/room_requests_controller.rb
class RoomRequestsController < ApplicationController

  before_action :require_signed_in!

  #should instead require that you are the specific user

  def new
    @room = Room.find(params[:room_id])
    render :new
  end

  def create
    @room = Room.find(params[:room_id])
    @request = RoomRequest.new(request_params)
    if @request.save
      @request.new_request_notification
      redirect_to user_room_requests_url(current_user)
    else
      flash.now[:errors] = @request.errors.full_messages
      render :new
    end
  end

  def index
    unless current_user.id == params[:user_id].to_i
      flash[:notice] = ["You can only see your own trips"]
      redirect_to root_url
      return
    end
    @user = User.find(params[:user_id])
    @requests = @user.requests_to_stay#.where("status != 'CANCELLED'")
    @trips = @requests
    if request.xhr?
      render "room_requests/trips"
    else
      render :index
    end
  end

  def approve
    @request = RoomRequest.find(params[:id])
    @request.approve!
    redirect_to manage_room_url(@request.room)
  end

  def deny
    @request = RoomRequest.find(params[:id])
    @request.deny!
    redirect_to manage_room_url(@request.room)
  end

  def cancel
    @request = RoomRequest.find(params[:id])
    @request.cancel!
    redirect_to :back
  end

  private
  def request_params
    params.require(:request).permit(:start_date, :end_date, :status, :room_id,
    :guest_id, :num_guests)
  end

end

app/helpers/room_requests_helper.rb
module RoomRequestsHelper
end

app/views/room_requests/index.html.erb
<script>

  $(document).ready(function () {

    $('h4[data-status="APPROVED"]').addClass('green');
    $('h4[data-status="DENIED"]').addClass('red');
    $('h4[data-status="CANCELLED"]').addClass('red');

  });

</script>


<h2>Your Trips</h2>

<% unless @requests.empty? %>
    <section class="trips">

      <% @requests.each do |request| %>
        <article class="room-request group">

          <h3><%= request.room.display_title %></h3>

          <h4 class="status-tag" data-status="<%= request.status %>">
            <strong>
              <%= request.status %>
            </strong>
          </h4>

          <p class="request-details">
            Dates: <br>
            <%= format_time(request.start_date)%><br>
            to <%= format_time(request.end_date) %><br><br>
            Number of Guests: <%= request.num_guests %>
          </p>
          <div class="trip-links">
            <a href="<%= user_url(request.host) %>">Visit Your Host's Page</a>
            <a href="<%= room_url(request.room) %>">See The Space</a>

            <% if request.status == "PENDING" || request.status == "APPROVED"  %>

              <form action="<%= cancel_room_request_url(request) %>" method="post">
                <%= auth_token %>

                <p><input type="submit" value="Cancel"></p>
              </form>

            <% end %>
          </div>

        </article>

      <% end %>

    </section>
<% else %>

<h3>You have no current trips.</h3>

<% end %>


<!-- could later add a js "send your host a message" button right here -->


<!-- should i include the rooms when i get @requests in the controller? -->

app/views/room_requests/new.html.erb
<h2>Make a Request</h2>

  <h3>Availability</h3>

  <%= render "layouts/calendar", room: @room  %><br>

<form action="<%= room_room_requests_url(@room) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="request[guest_id]" value="<%= current_user.id %>">
  <input type="hidden" name="request[room_id]" value="<%= @room.id %>">
  <input type="hidden" name="request[status]" value="PENDING">

  <label for="start_date">Start Date</label>
  <input type="date" name="request[start_date]" value="" id="start_date">

  <label for="end_date">End Date</label>
  <input type="date" name="request[end_date]" value="" id="end_date">

  <label for="num_guests">Number of Guests</label>
  <select name="request[num_guests]" id="num_guests">
    <% (1..10).to_a.each do |num| %>
      <option value="<%= num %>"><%= num %></option>
    <% end %>
  </select>
<br><br>
  <p><input type="submit" value="You make that request!"></p>
</form>