config/routes.rb
Freebnb::Application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:index, :destroy] do
    resources :rooms, only: :index
    resources :room_requests, only: [:index]
    resources :message_threads, only: :index
    get  "/dashboard" => "dashboard#root"
  end

  resources :rooms do
    resources :room_requests, only: [:new, :create]
    get "manage", on: :member
    resources :availabilities, only: [:new]
  end

  resources :room_requests, only: [:show, :destroy, :update] do
    post "approve", on: :member
    post "deny", on: :member
    post "cancel", on: :member
  end

  resources :notifications, only: [:index, :show]

  resources :reviews, only: [:create, :detroy]

  resources :messages, only: [:create]

  resources :message_threads, only: :show

  resources :availabilities, only: [:create]

  get '/search' => 'pages#search'

  root to: "rooms#index"

end

app/views/layouts/_calendar.html.erb
  <div class="datepicker" ></div>

  <script >

    $(function() {

      var convertDateToUTC = function (date) { 
        return new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getUTCHours(), date.getUTCMinutes(), date.getUTCSeconds()); 
    }

      $(".datepicker").datepicker({

        beforeShowDay: function(date) {
          var y = new Array()

          // compare date against approved requests
          <% unless room.approved_requests.empty? %>
              var a =(
            <% room.approved_requests.each do |x| %>
            (date < convertDateToUTC(new Date(<%= to_ms(x.start_date) %>)) || 
            date > convertDateToUTC(new Date(<%= to_ms(x.end_date) %>))) &&
            <% end %> true);
          <% else %>
            var a = true
          <% end %>

          // compare date against availabilities
          <% unless room.availabilities.empty? %>
            var b =(<% room.availabilities.each do |x| %>
                      (date >= convertDateToUTC(new Date(<%= to_ms(x.start_date) %>)) && date <= convertDateToUTC(new Date(<%= to_ms(x.end_date) %>))) ||
                    <% end %> false);
          <% else %>
            var b = false
          <% end %>

          y.push( (a && b) )
          y.push( (a && b) ? "" : "red")
          return y;
        }

      });
    });
  </script>

app/views/layouts/_room_request.html.erb
<article class="room-request">

  <%= "Status: #{ request.status }" %><br>

  <%= "#{ MAKE_NICE[room.home_type] } in #{ MAKE_NICE[room.address_city] }" %>

  <p>
    <%= "This reservation starts on #{ format_time(request.start_date) }, ends on #{ format_time(request.end_date) } and is for #{ request.num_guests }." %>
  </p>

  <%= "Made #{ time_ago_in_words(request.created_at) } ago." %>


</article>

app/views/layouts/_room_smail.html.erb
<article>

  <%= "#{ MAKE_NICE[room.home_type] } in #{ MAKE_NICE[room.address_city] }" %>

</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>treebnb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!-- calendar style -->
  <link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/ui-darkness/jquery-ui.css" rel="stylesheet">

</head>

<nav class="primary group">
  <div class="header-wrap group">
    <a href="<%= root_url %>"><h1 class="logo-primary"><i class="fa fa-globe"></i> treebnb</h1></a>

    <ul class="primary-controls group">
      <% if current_user %>

        <li id="controls">
          <a href="<%= user_url(current_user) %>">
            <img src="<%= current_user.avatar.url(:thumb) %>" id="user-nav-img">
            <%= current_user.fname %> <i class="fa fa-caret-down"></i>
          </a>
          <ul class="user-controls">

            <li>
              <a href="<%= user_dashboard_url(current_user) %>">
                Dashboard
              </a>
            </li>

            <li>
              <a href="<%= user_room_requests_url(current_user) %>">
                My Trips
              </a>
            </li>

            <li>
              <a href="<%= user_rooms_url(current_user) %>">
                My Listings
              </a>
            </li>

            <li>
              <a href="<%= user_url(current_user) %>">
                View Profile
              </a>
            </li>

            <li>
              <a href="<%= edit_user_url(current_user) %>">
                Edit Profile
              </a>
            </li>

            <li id="signout-li">
              <form action="<%= session_url %>" method="post" >
                <input type="hidden" name="_method" value="delete">
                <%= auth_token %>
                <input id="signout-button" type="submit" value="Sign Out">
              </form>
            </li>
          </ul>
        </li>

        <li id="notifications">
          <a href="<%= notifications_url %>">
            <img src="https://s3.amazonaws.com/freebnb_dev/icons/mail_icon.png"
            id="mail-icon">
            <strong id="notification-count">
              <%= "#{ num_notifications }" %>
            </strong>
          </a>
          <ul class="dropdown group">

              <li>
                <a href="<%= user_message_threads_url(current_user) %>">
                  My Messages
                </a>
              </li>

              <li>
                <a href="<%= notifications_url %>">
                  See All Notifications
                </a>
              </li>


            <% current_user.notifications.unread.order("created_at DESC").each do |notification| %>
              <li>
                <a href="<%= notification_url(notification) %>">
                  <%= notification.text %>
                </a>
              </li>
            <% end %>
          </ul>
        </li>

        <li>
          <a class="button-to-list" href="<%= new_room_url %>">
            LIST YOUR SPACE
          </a>
        </li>

      <% else %>

        <li>
          <a href="<%= new_user_url %>">
            sign up
          </a>
        </li>
        /
        <li>
          <a class="open-modal" href="<%= new_session_url %>">
            sign in
          </a>
        </li>

      <% end  %>
    </ul>
  </div>
</nav>


<body>


<script>

  window.openModal = function(event){
    event.preventDefault();
    $("#modal").addClass("is-active");
  }

  window.closeModal = function(event){
    $("#modal").removeClass("is-active");
  }

  $(document).ready(function(){
    $("body").on("click", ".open-modal", window.openModal);
    $("body").on("click", ".close-modal", window.closeModal);

    $('#demo-login').click(function (event) {
      event.preventDefault();
      var $tar = $(event.currentTarget);
      var $form = $tar.parent();

      var $email = $form.find('#email')
      $email.val("demo@example.com")

      var $pw = $form.find('#password')
      $pw.val("secret")

    });
  });

</script>


  <section id="modal" class="modal">
    <article class="modal-content">


        <span class="modal-x close-modal">&times;</span>
        <h2>Sign In</h2><br>

        <form action="<%= session_url %>" method="post">

          <%= auth_token %>

          <label for="email">Email</label>
          <input type="text" name="user[email]" value="" id="email">

          <label for="password">Password</label>
          <input type="password" name="user[password]" value="" id="password">
        <br><br>
          <input type="submit" value="Sign In">
          <button id="demo-login">Demo</button>
        </form>

    </article>

    <div class="modal-screen close-modal"></div>
  </section>


  <section class="main group">

    <% if flash[:errors] %>
        <section class="errors">
            <% flash[:errors].each do |error| %>
              <p><%= error %></p>
            <% end %>
        </section>
          <% end %>

          <% if flash[:notice] %>
        <section class="notices">
            <% flash[:notice].each do |notice| %>
              <p><%= notice %></p>
            <% end %>
        </section>
      <% end %>

    <%= yield %>
  </section>

  <footer class="footer group">

    <small class="footer-copy">
      &copy; 2014 treebnb. All rights reserved.
    </small>

    <nav class="footer-links">
      <ul class="group">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Privacy</a></li>
      </ul>
    </nav>

  </footer>

</body>
</html>